FROM scratch AS model-download-stage

# ADD https://huggingface.co/lmstudio-community/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q3_K_L.gguf?download=true model.gguf

COPY ./models/Llama-3.2-1B-Instruct-Q3_K_L.gguf ./model.gguf

FROM scratch AS tokenizer-download-stage

ADD https://huggingface.co/NousResearch/Meta-Llama-3-8B-Instruct/resolve/main/tokenizer.json?download=true tokenizer.json

FROM rust:1.86 AS build-stage

WORKDIR /usr/src/app

RUN apt update && apt install --no-install-recommends -y \
    libssl-dev \
    pkg-config

COPY Cargo.toml Cargo.lock ./
COPY ./src/ ./src/

RUN cargo build --locked --release

FROM debian:bookworm-slim AS final-stage

RUN apt update && apt install --no-install-recommends -y \
    libssl-dev \
    pkg-config \
    ca-certificates

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/target/release/socratic-chat-bot ./socratic-chat-bot

COPY --from=model-download-stage model.gguf ./model.gguf
COPY --from=tokenizer-download-stage tokenizer.json ./tokenizer.json

COPY ./static ./static
COPY ./templates ./templates

ARG VERSION
ENV VERSION=${VERSION}

CMD ["./socratic-chat-bot"]
